# Generated by Django 4.2.6 on 2024-01-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tournament',
            field=models.CharField(max_length=50),
        ),
    ]
