export enum RoomActionType {
    CREATE_UPDATE_ROOM_SUCCESS = "CREATE_UPDATE_ROOM_SUCCESS",
    CREATE_UPDATE_ROOM_FAIL = "CREATE_UPDATE_ROOM_FAIL",
    JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS",
    JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL",
    GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS",
    GET_ROOMS_FAIL = "GET_ROOMS_FAIL",

}