export enum RoomActionType {
    CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS",
    CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL",
    UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS",
    UPDATE_ROOM_FAIL = "UPDATE_ROOM_FAIL",
    JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS",
    JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL",
    LOAD_ROOM_DETAILS_SUCCESS = "LOAD_ROOM_DETAILS_SUCCESS",
    LOAD_ROOM_DETAILS_FAIL = "LOAD_ROOM_DETAILS_FAIL",
    USER_IN_ROOM_SUCCESS = "USER_IN_ROOM_SUCCESS",
    USER_IN_ROOM_FAIL = "USER_IN_ROOM_FAIL",
    LEAVE_ROOM_SUCCESS = "LEAVE_ROOM_SUCCESS",
    LEAVE_ROOM_FAIL = "LEAVE_ROOM_FAIL",
}