# Generated by Django 4.2.6 on 2024-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='Question')),
                ('choice1', models.CharField(max_length=100, verbose_name='Choice 1')),
                ('choice2', models.CharField(max_length=100, verbose_name='Choice 2')),
                ('choice3', models.CharField(max_length=100, verbose_name='Choice 3')),
                ('correct_choice', models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3')], max_length=100, verbose_name='Correct Choice')),
            ],
        ),
    ]
