# Generated by Django 4.2.6 on 2024-01-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('Italy', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3')], max_length=100, verbose_name='Correct Choice'),
        ),
    ]
