# Generated by Django 4.2.6 on 2024-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='roomCode',
            field=models.CharField(default='', max_length=8, verbose_name='Room Code'),
            preserve_default=False,
        ),
    ]
