# Generated by Django 4.2.6 on 2024-01-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_roomcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='roomCode',
            new_name='room_code',
        ),
    ]
