# Generated by Django 4.2.6 on 2024-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_roomcode_question_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='current_index',
            field=models.IntegerField(default=0, verbose_name='Current Index'),
        ),
    ]
