# Generated by Django 4.2.6 on 2024-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correct Choice'),
        ),
    ]
